### ISSUE TITLE
requires latest CMake version for apparently no good reason

### ISSUE THREAD

**Issue by meutzitzu** [Kravantokh/OpenGL_GLEW_GLFW_template#1]
Be honest, do you **absolutely** need CMake version 3.22.2 ?

**Comment by meutzitzu** [comment]
from my findings it works perfectly fine with CMake 3.16

**Comment by Kravantokh** [comment]
Until I find an automatic way of detecting the minimum version I will edit CMakeLists.txt to make it require 3.16 then.
